on:
    push:
        branches:
            - main
jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1

            - name: Install and build
              run: |
                  yarn install
                  yarn build:deploy

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.0
              with:
                  branch: gh-pages
                  folder: build/deploy
